export enum CodeErrorsEnum {
  INVALID_DATA = 'INVALID_DATA',
  DRIVER_NOT_FOUND = 'DRIVER_NOT_FOUND',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',
  INVALID_DISTANCE = 'INVALID_DISTANCE',
  NO_RIDES_FOUND = 'NO_RIDES_FOUND',
}
