version: '3.9'

volumes:
  app-vol:
  node-modules-vol:
  mssql-vol:
  keycloak-vol:
  redis-vol:

networks:
  app-network:
    name: app-network

services:
  base: &base
    hostname: base
    image: node:20-alpine
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
      - node-modules-vol:/home/node/app/node_modules
    networks:
      - app-network

  app:
    <<: *base
    hostname: app
    env_file:
      - ./.env
    ports:
      - 3003:3003
      - 9229:9229
    command: ash -c "yarn install && yarn dev"

  redis:
    hostname: redis
    image: 'redis:alpine'
    ports:
      - 6379:6379
    volumes:
      - redis-vol:/home/node/app/data/redis
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - 8081:8081
    depends_on:
      - redis
    networks:
      - app-network

  specs:
    <<: *base
    command: ash -c "yarn install && yarn test"
    env_file:
      - ./.env
    environment:
      NODE_ENV: local
